name: CI
on: pull_request

jobs:
  Test:
    runs-on:
      - self-hosted
      - CI-CD

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run actionlint
        run: actionlint .github/workflows/CI.yml -ignore 'label "CI-CD" is unknown'

      - name: Run codespell
        run: codespell --enable-colors

      - name: Run mdl
        run: mdl --style .github/workflows/mdl_style.rb .
